services:
  - type: web
    name: hamsafar-book-center
    env: php
    plan: free
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:10000 router.php
    envVars:
      - key: PORT
        value: 10000
